# Generated by Django 5.0.14 on 2026-08-05 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('delegates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=150)),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('mrz_data', models.TextField(blank=True, help_text='AI/OCR MRZ raw text (ভবিষ্যৎ ফিচার)')),
                ('signature_scan', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('passport_scan', models.ImageField(blank=True, null=True, upload_to='passports/')),
                ('holder_photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_process', 'In Process'), ('visa_approved', 'Visa Approved'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='received', max_length=25)),
                ('remark', models.TextField(blank=True)),
                ('ocr_processed', models.BooleanField(default=False)),
                ('ai_visa_detected', models.BooleanField(blank=True, help_text='AI Visa Detection ফলাফল (ভবিষ্যৎ)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passports', to='agents.agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passports_created', to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passports', to='delegates.delegate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PassportMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='passports.passport')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='passport',
            index=models.Index(fields=['passport_number'], name='passports_p_passpor_657dab_idx'),
        ),
        migrations.AddIndex(
            model_name='passport',
            index=models.Index(fields=['status'], name='passports_p_status_665cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='passport',
            index=models.Index(fields=['expiry_date'], name='passports_p_expiry__326b13_idx'),
        ),
    ]
