# Generated by Django 5.0.14 on 2026-08-05 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=150)),
                ('airline_name', models.CharField(max_length=150)),
                ('pnr', models.CharField(max_length=50, verbose_name='PNR')),
                ('flight_number', models.CharField(max_length=50)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('requested', 'Ticket Requested'), ('booking_in_progress', 'Booking in Progress'), ('confirmed', 'Ticket Confirmed'), ('issued', 'Ticket Issued'), ('travel_completed', 'Travel Completed'), ('cancelled', 'Ticket Cancelled'), ('refunded', 'Ticket Refunded')], default='requested', max_length=25)),
                ('e_ticket_file', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_tickets', to='passports.passport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
