# Generated by Django 5.0.14 on 2026-08-05 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('delegates', '0001_initial'),
        ('passports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_country', models.CharField(max_length=100)),
                ('visa_category', models.CharField(blank=True, max_length=100)),
                ('application_number', models.CharField(blank=True, max_length=100)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('application_received', 'Application Received'), ('document_verified', 'Document Verified'), ('submitted', 'Submitted'), ('under_processing', 'Under Processing'), ('additional_document_required', 'Additional Document Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('visa_collected', 'Visa Collected'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered'), ('closed', 'Closed')], default='application_received', max_length=35)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('visa_issue_date', models.DateField(blank=True, null=True)),
                ('visa_expiry_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, help_text='Visa PDF/Image copy', null=True, upload_to='visa_docs/')),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_applications', to='agents.agent')),
                ('delegate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_applications', to='delegates.delegate')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_applications', to='passports.passport')),
                ('processing_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisaStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=35)),
                ('new_status', models.CharField(max_length=35)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visa_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='visa.visaapplication')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visaapplication',
            index=models.Index(fields=['status'], name='visa_visaap_status_dfd8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='visaapplication',
            index=models.Index(fields=['destination_country'], name='visa_visaap_destina_0fdb6d_idx'),
        ),
    ]
