# Generated by Django 5.0.14 on 2026-08-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Ayesha Khan Singapore Overseas', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('auto_backup_enabled', models.BooleanField(default=False)),
                ('backup_frequency_days', models.PositiveIntegerField(default=7)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('passport_expiry_alert_days', models.PositiveIntegerField(default=30, help_text='মেয়াদ শেষ হওয়ার কত দিন আগে রিমাইন্ডার দেখাবে')),
                ('visa_expiry_alert_days', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Setting',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
